### ISSUE TITLE
checklist for CRAN release 0.9.20

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1124]
(Note: I will edit this in-place, as I do the tests.)

**Phase 1 (develop branch)**

Commit 58b4b4ada8dc1cc6d7b527af92952c0b553a038e 
* [x] DK does RStudio build, test, and check
* [x] DK does the CTD tests suite (in `tests_private`, do `make clean` and then `make`)
* [x] DK checks that this passes through TravisCI without problems
* [x] DK check on winbuilder (stable) -- 1 NOTE (on size); see https://win-builder.r-project.org/Xdw8Jzz5eKyB/
* [x] DK check on winbuilder (develop) -- 1 NOTE (on size); see https://win-builder.r-project.org/AlpxAXJj79En/

**Phase 2 (master branch)**

Commit 4c480a960e7f8873e2e9bf947ebe7d1c40cfe79d 
* [x] DK does RStudio build+check, plus code-diagnostic scan
* [x] DK does the CTD tests suite (in `tests_private`, do `make clean` and then `make`)
* [x] DK checks that this passes through TravisCI without problems
* [x] DK check on winbuilder (stable) -- 1 NOTE (on size); see https://win-builder.r-project.org/5sWl2tdEC4ra/
* [x] DK check on winbuilder (develop) -- 1 NOTE (on size); see https://win-builder.r-project.org/515092a419F8/

NOTE: last night, the same build 4c480a960e7f8873e2e9bf947ebe7d1c40cfe79d got URL errors for a lot of nortek sites. OK this morning though ... so I still plan to submit this morning, as is.

**Comment by dankelley** [comment]
@richardsc Unless you have other items for the checklist, I think we are a "go" for a CRAN submission tomorrow morning. (It could be today but I'd prefer to wait until the time we had in mind, probably 0700h tomorrow)

**Comment by richardsc** [comment]
No other actions from me. I'm good to wait until tomorrow morning for a submission.

**Comment by dankelley** [comment]
I think we are good to go. I just did a new checklist (in the first comment). The only problem is that now we get a URL lookup failure with R-devel. But that URL was OK earlier today, and likely it will be OK later today. It's at WHOI, which was probably just down in the 5-second interval that R was checking. I do not want to drop a WHOI link because of a momentary failure. I may just put in a test build tomorrow morning, and if that's okay, I'll submit; otherwise I will change the URL class from `\link{}` to `\samp{}` and submit.  (My idea is that if WHOI is unaccessible for over 12 hours, then WHOI is too unreliable for me to argue to the CRAN folks that it deserves a `link{}`)

**Comment by dankelley** [comment]
Uploaded to CRAN. Last night, the winbuilder was giving errors on a lot of nortek websites but they worked ok today. I would have removed the links, had they been faulty today. There seems no use in getting into an argument with CRAN maintainers over broken links, if they are broken two days in a row.

I will close this issue when the submission goes through (normally takes under 2 days) or I will post more comments here, if more fixes are required.

**Comment by dankelley** [comment]
I got the email that is on CRAN now. Usually that means binaries will start appearing in a day or two.
