### ISSUE TITLE
f2f 20180515 workplan

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1422]
Workplan -- all in the "dk" branch, which is where flags are being developed, at least for a few more days

**DK**
* [x] do not permit use of names for flags in `handleFlags` (done in "dk branch commit b1d8b277f87755ebecb7ba5d4ac0e39c00e18b92)
* [x] do not permit use of names for flags in `initializeFlags` (done in "dk branch commit b1d8b277f87755ebecb7ba5d4ac0e39c00e18b92)
* [x] do not permit negative flags in `handleFlags` (done in "dk branch commit b1d8b277f87755ebecb7ba5d4ac0e39c00e18b92)
* [x] remove default `handleFlags` arguments for all object classes (done in "dk branch commit b1d8b277f87755ebecb7ba5d4ac0e39c00e18b92)
* [x] remove the special-case for `handleFlags,ctd-method` regarding salinityBottle being used as a replacement for salinity (done in "dk branch commit b1d8b277f87755ebecb7ba5d4ac0e39c00e18b92)
* [x] move that special-case for salinityBottle to the docs

**CR**
* [x] suggest additions to `tests/testthat/test_flags.R` for the argo case

**Comment by richardsc** [comment]
I'm looking at the Argo tests, but of course they will change shortly when the 4th bullet above gets implemented (removing default handleFlags arguments).

**Comment by richardsc** [comment]
I think the tests are a good exercising of the argo flag capabilities. We might add more, but those are good examples of what's possible and therefore good tests.

I was about to close but then it looked like you added another bullet ... ?

**Comment by dankelley** [comment]
Oh, just checking: my new bullet is done (below is the code in the example) so I'm going to tick the box and close the issue.
```R
# 2. Use bottle salinity, if it is good and ctd is bad
replace <- 2 == stn[["salinityBottleFlag"]] && 2 != stn[["salinityFlag"]]
S <- ifelse(replace, stn[["salinityBottle"]], stn[["salinity"]])
STN2 <- oceSetData(stn, "salinity", S)
```
